### ISSUE TITLE
error CS1503: Argument 1: cannot convert from 'void*' to 'int*'

### ISSUE THREAD

**Issue by parsue** [AnnulusGames/BurstLinq#5] opened 2024-03-12 08:06 UTC
Mulitple lines error in following files:
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Average.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Contains.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Max.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Min.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.SequenceEqual.cs
-----
Unity version 2023.2.13.f1
Burst: 1.8.12

**Comment by ckocank** [comment] 2024-03-17 11:47
same error

**Comment by nuskey8** [comment] 2024-03-21 08:01
This error seems to be caused by the version of the Collections package. `GetUnsafePtr()` returns `void*` for old Collections.

Looks like I need to add an explicit cast to prevent the error.

**Comment by nuskey8** [comment] 2024-03-21 08:09
Fixed in #7.

**Closed as completed by nuskey8** 2024-03-21 08:09 UTC
